DROP TABLE SYSTEM_KEYS;

CREATE TABLE SYSTEM_KEYS (KEY_NAME VARCHAR(256) PRIMARY KEY, KEY_VALUE VARCHAR(1024));

DROP TABLE TOKEN_KEY;

CREATE TABLE TOKEN_KEY (VAL VARCHAR(256));

DROP TABLE KEYS;

CREATE TABLE KEYS (KEY_NAME VARCHAR(256) PRIMARY KEY, KEY_VALUE VARCHAR(1024));

DROP TABLE IDENTITY_BLACKLIST;

CREATE TABLE IDENTITY_BLACKLIST (IDENT VARCHAR(256) PRIMARY KEY);

